[package]
name = "ndarray-image"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.22.1"
ndarray = "0.12.1"

[dev-dependencies]
structopt = "0.2.18"

